[package]
name = "minesweeper"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.5"
crossterm = "0.25.0"

[dependencies.sdl2]
version = "0.35.2"
default-features = false
features = ["ttf"]
